# Generated by Django 2.2.2 on 2020-08-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invConfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invconfig',
            name='fpTipo',
            field=models.CharField(choices=[('D', 'Inductive'), ('A', 'Capacitive')], max_length=1),
        ),
    ]
