# Generated by Django 2.2.6 on 2019-10-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='estTipo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
