# Generated by Django 2.2.7 on 2019-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_campus_esttipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixasIP',
            fields=[
                ('pref', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descri', models.CharField(max_length=15)),
            ],
        ),
    ]
