# Generated by Django 2.2.2 on 2020-07-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_faixasip'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatorPot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=4)),
                ('fp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fpTipo', models.CharField(choices=[('T', 'Atraso'), ('V', 'Avanço')], max_length=1)),
                ('fpMin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fpMax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fpUpdateStatus', models.IntegerField()),
                ('fpUpdateTime', models.DateTimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Campus')),
            ],
        ),
    ]
