# Generated by Django 2.2.2 on 2020-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_fatorpot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatorpot',
            name='descri',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fatorpot',
            name='fp',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='fatorpot',
            name='fpMax',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='fatorpot',
            name='fpMin',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
