# Generated by Django 2.2.2 on 2020-07-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20200720_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=4)),
                ('descri', models.TextField()),
                ('fp', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fpTipo', models.CharField(choices=[('D', 'Delay'), ('A', 'Advance')], max_length=1)),
                ('fpMin', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fpMax', models.DecimalField(decimal_places=2, max_digits=3)),
                ('limPot', models.IntegerField()),
                ('UpdateStatus', models.CharField(choices=[('A', 'Applied'), ('U', 'Updated')], max_length=1)),
                ('UpdateTime', models.DateTimeField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Campus')),
            ],
            options={
                'unique_together': {('campus', 'nome')},
            },
        ),
        migrations.DeleteModel(
            name='FatorPot',
        ),
    ]
