# Generated by Django 2.2.2 on 2020-07-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20200720_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvConfigTokens',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('inverters', models.ManyToManyField(to='monitor.InvConfig')),
            ],
        ),
    ]
