# Generated by Django 2.2.2 on 2020-08-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_invconfigtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invconfigtokens',
            name='inverters',
        ),
        migrations.DeleteModel(
            name='InvConfig',
        ),
        migrations.DeleteModel(
            name='InvConfigTokens',
        ),
    ]
