# Generated by Django 2.2.2 on 2020-09-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20200804_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaixasIP',
        ),
    ]
